language: go
sudo: false

matrix:
  include:
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.9

branches:
  only:
    - master

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/mock/mockgen

install:
  - make generate

script:
  - GO15VENDOREXPERIMENT=1 go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
