// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/anexia-it/go-structconf/storage (interfaces: Storage)

package structconf

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *_MockStorageRecorder
}

// Recorder for MockStorage (not exported)
type _MockStorageRecorder struct {
	mock *MockStorage
}

func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &_MockStorageRecorder{mock}
	return mock
}

func (_m *MockStorage) EXPECT() *_MockStorageRecorder {
	return _m.recorder
}

func (_m *MockStorage) ReadConfig() ([]byte, error) {
	ret := _m.ctrl.Call(_m, "ReadConfig")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStorageRecorder) ReadConfig() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReadConfig")
}

func (_m *MockStorage) WriteConfig(_param0 []byte) error {
	ret := _m.ctrl.Call(_m, "WriteConfig", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStorageRecorder) WriteConfig(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WriteConfig", arg0)
}
